# Generated by Django 5.2.7 on 2025-10-23 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desarrolladora_model',
            fields=[
                ('id_desarrolladora', models.IntegerField(primary_key=True, serialize=False)),
                ('pais', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('logo', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'desarrolladora',
            },
        ),
        migrations.CreateModel(
            name='Editora_model',
            fields=[
                ('id_editoria', models.IntegerField(primary_key=True, serialize=False)),
                ('pais', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('logo', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'editora',
            },
        ),
        migrations.CreateModel(
            name='Esrb_model',
            fields=[
                ('id_esrb', models.IntegerField(primary_key=True, serialize=False)),
                ('clasificacion', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'esrb',
            },
        ),
        migrations.CreateModel(
            name='Genero_model',
            fields=[
                ('id_genero', models.IntegerField(primary_key=True, serialize=False)),
                ('genero', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'genero',
            },
        ),
        migrations.CreateModel(
            name='Plataforma_model',
            fields=[
                ('id_plataforma', models.IntegerField(primary_key=True, serialize=False)),
                ('director', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('logo', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'plataforma',
            },
        ),
        migrations.CreateModel(
            name='Resena_model',
            fields=[
                ('id_resena', models.IntegerField(primary_key=True, serialize=False)),
                ('fuente', models.CharField(max_length=50)),
                ('puntuacion', models.IntegerField()),
                ('fecha_resena', models.DateField()),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'resena',
            },
        ),
        migrations.CreateModel(
            name='Titulo_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('fecha_lanzamiento', models.DateField()),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('etiquetas', models.CharField(max_length=50)),
                ('portada', models.ImageField(upload_to='')),
                ('desarrolladora', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='AlanJorgeApp.desarrolladora_model')),
                ('editora', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='AlanJorgeApp.editora_model')),
                ('esrb', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='AlanJorgeApp.esrb_model')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='AlanJorgeApp.genero_model')),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='AlanJorgeApp.plataforma_model')),
            ],
            options={
                'db_table': 'juego',
            },
        ),
    ]
